local_backend: true

backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# Location where files will be stored in the repo.
media_folder: "src/assets/images"

# The src attribute for uploaded media.
public_folder: "src/assets/images"

collections:
- name: "general"
  label: "Általános beállítások"
  files:
    - label: "Bejelentés legfelül"
      name: "announcement"
      file: "src/content/general/announcement.json"
      fields:
        - label: "Jelenjen meg?"
          name: "enabled"
          widget: "boolean"
        - label: "Szöveg"
          name: "text"
          widget: "text"
        - label: "Link"
          name: "link"
          widget: "string"

- name: "fixed-pages"
  label: "Kötött oldalak"
  files:
    - label: "Kezdőlap"
      name: "home"
      file: "src/content/fixed-pages/home.json"
      fields:
        - label: "Üdvözlő cím"
          name: "greetingTitle"
          widget: "text"
        - label: "Üdvözlő alcím"
          name: "greetingSubtitle"
          widget: "text"
        - label: "Bemutatkozó cím"
          name: "aboutTitle"
          widget: "text"
        - label: "Bemutatkozó szöveg"
          name: "aboutText"
          widget: "markdown"

- name: "sights"
  label: "Látnivaló"
  folder: "src/content/sights"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "image"
      widget: "image"
      allow_multiple: false
    - label: "Link"
      name: "link"
      widget: "string"

- name: "rooms"
  label: "Szoba"
  folder: "src/content/rooms"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "gallery"
      widget: "list"
      field: 
        label: "Kép"
        name: "image"
        widget: "image"
