backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# Location where files will be stored in the repo.
media_folder: "src/assets/images"

# The src attribute for uploaded media.
public_folder: "src/assets/images"

collections:
- name: "general"
  label: "Általános beállítások"
  files:
    - label: "Logó"
      name: "logo"
      file: "src/content/general/logo.json"
      fields:
        - label: "Logó"
          name: "image"
          widget: "image"
          choose_url: false
    - label: "Jogi szövegek"
      name: "legal"
      file: "src/content/general/legal.json"
      fields:
        - label: "Adatvédelmi szabályzat"
          name: "privacy"
          widget: "markdown"
        - label: "Általános szerződési feltételek"
          name: "terms"
          widget: "markdown"
    - label: "Lábléc"
      name: "footer"
      file: "src/content/general/footer.json"
      fields:
        - label: "Bal oldali cím"
          name: "leftTitle"
          widget: "text"
        - label: "Bal oldali szöveg"
          name: "leftContent"
          widget: "markdown"
        - label: "Népszerű linkek"
          name: "popularLinks"
          widget: "list"
          fields:
            - label: "Név"
              name: "title"
              widget: "text"
            - label: "Link"
              name: "link"
              widget: "string"
        - label: "Hírlevél szöveg"
          name: "newsletterContent"
          widget: "markdown"
    - label: "Bejelentés legfelül"
      name: "announcement"
      file: "src/content/general/announcement.json"
      fields:
        - label: "Jelenjen meg?"
          name: "enabled"
          widget: "boolean"
        - label: "Szöveg"
          name: "text"
          widget: "text"
        - label: "Link"
          name: "link"
          widget: "string"
    - label: "Elérhetőségek"
      name: "contact"
      file: "src/content/general/contact.json"
      fields:
        - label: "Cím"
          name: "address"
          widget: "text"
        - label: "Telefonszám"
          name: "phone"
          widget: "string"
        - label: "Email"
          name: "email"
          widget: "string"
        - label: "Facebook"
          name: "facebook"
          widget: "string"
        - label: "Instagram"
          name: "instagram"
          widget: "string"
    - label: "SZÉP Kártya"
      name: "pretty"
      file: "src/content/general/pretty.json"
      fields:
        - label: "Elfogadóhely kép"
          name: "image"
          widget: "image"
          choose_url: false

- name: "fixed-pages"
  label: "Kötött oldalak"
  files:
    - label: "Kezdőlap"
      name: "home"
      file: "src/content/fixed-pages/home.json"
      fields:
        - label: "Üdvözlő cím"
          name: "greetingTitle"
          widget: "text"
        - label: "Üdvözlő alcím"
          name: "greetingSubtitle"
          widget: "text"

        - label: "Bannerek"
          name: "banners"
          widget: "list"
          fields:
            - label: "Cím"
              name: "title"
              widget: "text"
            - label: "Tartalom"
              name: "content"
              widget: "markdown"    
            - label: "CTA gomb felirat"
              name: "ctaButtonLabel"
              widget: "text"
            - label: "CTA gomb link"
              name: "ctaButtonLink"
              widget: "string"
        - label: "Szolgáltatások blokk cím"
          name: "servicesTitle"
          widget: "text"
        - label: "Szolgáltatások blokk tartalom"
          name: "servicesContent"
          widget: "markdown"
        - label: "Szolgáltatások"
          name: "services"
          widget: "list"
          fields:
            - label: "Név"
              name: "title"
              widget: "text"
            - label: "Leírás"
              name: "description"
              widget: "text"
            - label: "Ikon"
              name: "icon"
              widget: "image"
              choose_url: false
        - label: "Blokkok"
          name: "blocks"
          widget: "list"
          fields:
            - label: "Cím"
              name: "title"
              widget: "text"
            - label: "Tartalom"
              name: "content"
              widget: "markdown"    
            - label: "CTA gomb felirat"
              name: "ctaButtonLabel"
              widget: "text"
            - label: "CTA gomb link"
              name: "ctaButtonLink"
              widget: "string"
        - label: "Élmények blokk cím"
          name: "experiencesTitle"
          widget: "text"
        - label: "Élmények blokk tartalom"
          name: "experiencesContent"
          widget: "markdown"
        - label: "Élmények"
          name: "experiences"
          widget: "list"
          fields:
            - label: "Név"
              name: "title"
              widget: "text"
            - label: "Leírás"
              name: "description"
              widget: "markdown"
            - label: "Ikon"
              name: "icon"
              widget: "image"
              choose_url: false
        - label: "SEO blokk cím"
          name: "seoTitle"
          widget: "text"
        - label: "SEO blokk tartalom"
          name: "seoContent"
          widget: "markdown"
        - label: "Kép"
          name: "gallery"
          widget: "list"
          field: 
            label: "Kép"
            name: "image"
            widget: "image"

    - label: "Szobáink"
      name: "rooms"
      file: "src/content/fixed-pages/rooms.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"

    - label: "Élmények"
      name: "experiences"
      file: "src/content/fixed-pages/experiences.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"
        - label: "Élmények"
          name: "experiences"
          widget: "list"
          fields:
            - label: "Név"
              name: "title"
              widget: "text"
            - label: "Kép"
              name: "image"
              widget: "image"
              choose_url: false
            - label: "Tartalom"
              name: "content"
              widget: "markdown"
      
    - label: "Galéria"
      name: "gallery"
      file: "src/content/fixed-pages/gallery.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"
        - label: "Kép"
          name: "gallery"
          widget: "list"
          field: 
            label: "Kép"
            name: "image"
            widget: "image"
            
    - label: "Látnivalók"
      name: "sights"
      file: "src/content/fixed-pages/sights.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Borítókép"
          name: "coverImage"
          widget: "image"
          choose_url: false

    - label: "Rólunk"
      name: "about"
      file: "src/content/fixed-pages/about.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"
    
    - label: "Kapcsolat"
      name: "contact"
      file: "src/content/fixed-pages/contact.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Gyakran ismételt kérdések"
          name: "faq"
          widget: "list"
          fields:
            - label: "Kérdés"
              name: "question"
              widget: "text"
            - label: "Válasz"
              name: "answer"
              widget: "markdown"

    - label: "Promóciók"
      name: "promotions"
      file: "src/content/fixed-pages/promotions.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"
        - label: "Promóciók"
          name: "promotions"
          widget: "list"
          fields:
            - label: "Cím"
              name: "title"
              widget: "text"
            - label: "Kép"
              name: "image"
              widget: "image"
              choose_url: false
            - label: "Tartalom"
              name: "content"
              widget: "markdown"
            - label: "Aktív?"
              name: "active"
              widget: "boolean"

- name: "additional-pages"
  label: "További oldal"
  folder: "src/content/additional-pages"
  create: true
  fields:
    - label: "Cím"
      name: "title"
      widget: "text"
    - label: "Alcím"
      name: "subtitle"
      widget: "string"
    - label: "Borítókép"
      name: "coverImage"
      widget: "image"
      choose_url: false
    - label: "Tartalom"
      name: "body"
      widget: "markdown"

- name: "sights"
  label: "Látnivaló"
  folder: "src/content/sights"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "image"
      widget: "image"
      allow_multiple: false
    - label: "Link"
      name: "link"
      widget: "string"

- name: "rooms"
  label: "Szoba"
  folder: "src/content/rooms"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "gallery"
      widget: "list"
      field: 
        label: "Kép"
        name: "image"
        widget: "image"
