local_backend: true

backend:
  name: git-gateway
  branch: master

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# Location where files will be stored in the repo.
media_folder: "src/assets/images"

# The src attribute for uploaded media.
public_folder: "src/assets/images"

collections:
- name: "general"
  label: "Általános beállítások"
  files:
    - label: "Logó"
      name: "logo"
      file: "src/content/general/logo.json"
      fields:
        - label: "Logó"
          name: "image"
          widget: "image"
          choose_url: false
    - label: "Bejelentés legfelül"
      name: "announcement"
      file: "src/content/general/announcement.json"
      fields:
        - label: "Jelenjen meg?"
          name: "enabled"
          widget: "boolean"
        - label: "Szöveg"
          name: "text"
          widget: "text"
        - label: "Link"
          name: "link"
          widget: "string"
    - label: "Elérhetőségek"
      name: "contact"
      file: "src/content/general/contact.json"
      fields:
        - label: "Cím"
          name: "address"
          widget: "text"
        - label: "Telefonszám"
          name: "phone"
          widget: "string"
        - label: "Email"
          name: "email"
          widget: "string"
        - label: "Facebook"
          name: "facebook"
          widget: "string"
        - label: "Instagram"
          name: "instagram"
          widget: "string"
    - label: "SZÉP Kártya"
      name: "pretty"
      file: "src/content/general/pretty.json"
      fields:
        - label: "Elfogadóhely kép"
          name: "image"
          widget: "image"
          choose_url: false

- name: "fixed-pages"
  label: "Kötött oldalak"
  files:
    - label: "Kezdőlap"
      name: "home"
      file: "src/content/fixed-pages/home.json"
      fields:
        - label: "Üdvözlő cím"
          name: "greetingTitle"
          widget: "text"
        - label: "Üdvözlő alcím"
          name: "greetingSubtitle"
          widget: "text"
        - label: "Bemutatkozó cím"
          name: "aboutTitle"
          widget: "text"
        - label: "Bemutatkozó szöveg"
          name: "aboutText"
          widget: "markdown"
        - label: "Kiemelt szolgáltatás"
          name: "featureHighlight"
          widget: "list"
          min: 3
          max: 3
          allow_add: false
          fields:
            - label: "Név"
              name: "title"
              widget: "string"
            - label: "Leírás"
              name: "description"
              widget: "string"
            - label: "Kép"
              name: "icon"
              widget: "image"
              choose_url: false
        - label: "Képes szolgáltatás"
          name: "imageFeatures"
          widget: "list"
          min: 1
          fields:
            - label: "Név"
              name: "title"
              widget: "string"
            - label: "Leírás"
              name: "content"
              widget: "markdown"
            - label: "Image"
              name: "image"
              widget: "image"
              choose_url: false
            - label: "A kép melyik oldalon jelenjen meg?"
              name: "imageSide"
              widget: "select"
              default: "right"
              options:
                - label: "Bal"
                  value: "left"
                - label: "Jobb"
                  value: "right"
        - label: "Csempés szolgáltatás"
          name: "tileFeatures"
          widget: "list"
          min: 1
          fields:
            - label: "Név"
              name: "title"
              widget: "string"
            - label: "Kép"
              name: "icon"
              widget: "image"
              choose_url: false

    - label: "Közvetlen foglalási ajánlat"
      name: "direct-booking"
      file: "src/content/fixed-pages/direct-booking.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Borítókép"
          name: "coverImage"
          widget: "image"
          choose_url: false
        - label: "Tartalom"
          name: "content"
          widget: "markdown"
    
    - label: "Látnivalók"
      name: "sights"
      file: "src/content/fixed-pages/sights.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Borítókép"
          name: "coverImage"
          widget: "image"
          choose_url: false

    - label: "Programajánlat"
      name: "guide"
      file: "src/content/fixed-pages/guide.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Borítókép"
          name: "coverImage"
          widget: "image"
          choose_url: false
        - label: "Tartalom"
          name: "content"
          widget: "markdown"

    - label: "Rólunk"
      name: "about"
      file: "src/content/fixed-pages/about.json"
      fields:
        - label: "Alcím"
          name: "subtitle"
          widget: "text"
        - label: "Tartalom"
          name: "content"
          widget: "markdown"

- name: "services"
  label: "Szolgáltatás"
  folder: "src/content/services"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kiemelt szolgáltatás? (Azaz, megjelenjen a nyitókép alatt?)"
      name: "highlight"
      widget: "boolean"
      default: false
    - label: "Ikon"
      name: "icon"
      widget: "image"
      allow_multiple: false
      choose_url: false
    - label: "Tartalom"
      name: "body"
      widget: "markdown"

- name: "additional-pages"
  label: "További oldal"
  folder: "src/content/additional-pages"
  create: true
  fields:
    - label: "Cím"
      name: "title"
      widget: "text"
    - label: "Alcím"
      name: "subtitle"
      widget: "string"
    - label: "Borítókép"
      name: "coverImage"
      widget: "image"
      choose_url: false
    - label: "Tartalom"
      name: "body"
      widget: "markdown"

- name: "sights"
  label: "Látnivaló"
  folder: "src/content/sights"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "image"
      widget: "image"
      allow_multiple: false
    - label: "Link"
      name: "link"
      widget: "string"

- name: "rooms"
  label: "Szoba"
  folder: "src/content/rooms"
  create: true
  fields:
    - label: "Név"
      name: "title"
      widget: "string"
    - label: "Leírás"
      name: "body"
      widget: "markdown"
    - label: "Kép"
      name: "gallery"
      widget: "list"
      field: 
        label: "Kép"
        name: "image"
        widget: "image"
